version: '3'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    restart: "no"
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge